server:
    port: 8899

spring:
    data:
        mongodb:
            database: grammarly
            auto-index-creation: true

downloadDir: C:/Users/plq/Downloads/
fileSaveDir: D:/selenium/download/
