server:
    port: 1008

spring:
    data:
        mongodb:
            host: 121.4.232.40
            port: 27017
            database: grammarly
            username: root
            authentication-database: admin
            password: 4qlPi9zeL1dqhtJ8
            auto-index-creation: true
#            uri: "mongodb://root:4qlPi9zeL1dqhtJ8@121.4.232.40:27017/grammarly?ssl=false"