server:
    port: 8899

spring:
    data:
        mongodb:
            host: 121.4.232.40
            port: 27017
            database: grammarly
            username: root
            authentication-database: admin
            password: 4qlPi9zeL1dqhtJ8
            auto-index-creation: true
#            uri: "mongodb://root:4qlPi9zeL1dqhtJ8@121.4.232.40:27017/grammarly?ssl=false"
    mail:
        properties:
            mail:
                smtp:
                    debug: true

logging:
    level:
        org.springframework.data.mongodb.core: DEBUG