# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 100
      min-spare: 5

spring:
  application:
    name: grammarly-plugin
  profiles:
    active: @spring.profiles.active@
  # jackson\u65F6\u95F4\u683C\u5F0F\u5316
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  freemarker:
    charset: utf-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates #配置模板所在目录

